name: deploy

on:
  push:
    branches:
      - main

env:
  GIT_USER: loveychen
  GIT_EMAIL: loveychen@live.com
  THEME_REPO: LouisBarranqueiro/hexo-theme-tranquilpeak
  THEME_BRANCH: master
  DEPLOY_REPO: loveychen/loveychen.github.io
  DEPLOY_BRANCH: main

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: themes/tranquilpeak
          fetch-depth: 0

      # - name: Checkout deploy repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ env.DEPLOY_REPO }}
      #     ref: ${{ env.DEPLOY_BRANCH }}
      #     path: .deploy_git
      #     fetch-depth: 0

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          cp _config.theme.yml themes/tranquilpeak/_config.yml

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy hexo
        run: |
          npm run clean
          npm run generate
          npm run deploy
